### ISSUE TITLE
TypeError: Cannot read property '$$phase' of null

### ISSUE THREAD

**Issue by expntly** [cotag/angular-safeapply#2]
"angular-safeapply": "~1.0.4"

Looking at safe-apply.js, this seems to happen here:

    if (force || !($scope.$$phase || $scope.$root.$$phase)) {

But I'm not sure whether this is on the first or second $$phase, tempted to think it's $root that's null.

My code does something like

    angular.module('...')
    .controller('...', ['$scope', ..., function($scope, ...) {
      $scope.init = function() {
        $scope.typeAheadEngine = new Bloodhound({
          remote: {
            ajax: {
              complete: function() {
                $scope.$safeApply(function() { $scope.searching = false; });  // <<== issue here
              },
            },
      ...

I don't have a way to reproduce yet.  Any idea what's going on?

**Comment by stakach** [comment]
I've experienced similar issues.
I assume you've only seen the issue on Chrome?
Chrome seems to over-optimise JS sometimes leading to weird and wonderful bugs.

See #1 who was experiencing the same issue. If you are able to reproduce and provide a solution I'll happily accept a pull request.

**Comment by 2i** [comment]
Please see https://github.com/cotag/angular-safeapply/pull/3. It is just the fastest solution, maybe not the best one.

**Comment by stakach** [comment]
Thanks @2i

**Comment by 2i** [comment]
@stakach Thanks to you for maintaining this bower package.
